### PR TITLE
Adds OS X as a target. I'm doing this to then have the meteor-ios project also target OS X

### PR DESCRIPTION
**Pull request by mathieutozer**
Todo: (could use some help!)
* For some reason the tests to remove the items fail - I looked into it and the keychain API is failing to remove them because it cant find them. Something is up with the query.

Signed-off-by: Mathieu Tozer <mathieutozer@gmail.com>

### CODE REVIEW

**Comment by hzalaz** [comment]
@mathieutozer thanks for the PR. Can you change the `.travis.yml` to run at least iOS tests which is why it's failing now?.

It's odd about the failing test, these are in OS X or iOS?

**Comment by mathieutozer** [comment]
I was running them on OS X, will look into the failure and update. Although
I still don't know why the removal function fails for OS X and not for iOS.
Any idea?
2015年5月4日(月) 6:49 Hernan Zalazar <notifications@github.com>:

**Comment by hzalaz** [comment]
Might be the query as you mentioned because I think an extra parameter is needed in OSX to fetch/delete items, I am far from an OS X expert :smile:, but I'll have to research a little bit more.
l can try running the tests from your fork, until you fix the travis.yml.

**Comment by mathieutozer** [comment]
Not sure why travis failed again - I was able to run those commands locally. Could you take a look please?

Also, should the pods be added to the commit? It doesn't look like it...

**Comment by hzalaz** [comment]
@mathieutozer I'll take a look later today.

**Comment by hzalaz** [comment]
@mathieutozer sorry but I am busy with other stuff so I couldn't check why the OS X test to remove entries fails. The latest commit fails in travis because you need to mark the scheme `A0SimpleKeychainOSX` as shared in Xcode, otherwise it will only stay in your mac :smile: .

If you can remove entries in your sample OS X app I'll merge this, once you fix the scheme issue, and deal with that failing test.

**Comment by hzalaz** [comment]
Also its trying to find the __Podfile__ here `Example/Podfile`. To make this quick, just make iOS test run and we'll see OS X tests later

**Comment by mathieutozer** [comment]
No worries I've been pretty busy too. Will fix those things so it's green and then move on.

**Comment by mathieutozer** [comment]
I'm pretty sure I have pushed the A0SimpleKeychainOSX scheme... let's see how this run goes

**Comment by mathieutozer** [comment]
Finally!

**Comment by mathieutozer** [comment]
Ping! Can we pull this?

**Comment by hzalaz** [comment]
I'll try to release this as soon as I can. I wanted to check the OS X tests issues and to merge everything to a single workspace (to keep my sanity :smile: ), but I am stuck with a lot of other stuff.

**Comment by mathieutozer** [comment]
No problems - let me know when it's ready to go!

**Pull request merged**
