### PR TITLE
Fix Pod Lib Lint Warnings

### PR DESCRIPTION
**Pull request by Y2JChamp**

### CODE REVIEW

**Comment by subdigital** [comment]
Any idea when this might be merged?

**Comment by cocojoe** [comment]
@subdigital how you are surfacing this warning? I checked out master and compiling on 9.3 for iOS. No code warnings,  only the usual update project settings as new Xcode.

**Comment by subdigital** [comment]
Version 0.8.0 is being pulled in via CocoaPods from Auth0.Swift (1.10.1).

image

**Comment by cocojoe** [comment]
Thanks, this is what I needed to see.  I use carthage and this doesn't show as it's not a Swift Compiler warning it's a cocoapods lint warning. No harm in tweaking in this along with some project updates for 9.3 👍

**Pull request merged**
