### PR TITLE
feat: added support for visionOS platform

### PR DESCRIPTION
**Pull request by desusai7**
#### feat: added support for visionOS platform

* Added a visionOS framework target and unit tests target for the framework.
* Added a visionOS sample app and linked it to the unit tests target.
* Updated all the ruby gems including cocoapods to support visionOS platform.
* Upgraded Xcode to version `15.2` and macos runner to `13-x-large` to support visionOS and its simulators.
* Dropped support for xcode 14, swift version 5.7, 5.8, and now the minimum required version of Xcode is 15 and Swift is 5.9. (This is done to support visonOS)
* Dropped support for iOS 13 & tvOS 13 platforms as per our support policy to support only last 4 major versions of any platform including the current major version.
* CI checks for visionOS will be tackled as part of PR #217 later as there are some issues with visionOS simulator on CI pipeline.

### ✅  Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Review by Widcket — COMMENTED** [review]
Do the list of platforms in `Platforms.swift` need updating? https://github.com/auth0/SimpleKeychain/blob/master/Package.swift#L6

**Comment by desusai7** [comment]
> Do the list of platforms in `Platforms.swift` need updating? https://github.com/auth0/SimpleKeychain/blob/master/Package.swift#L6

Tracking this in separate PR raised just now [here](https://github.com/auth0/SimpleKeychain/pull/218) as we will have to bump up the minimum supported swift version to 5.9 and drop support for Xcode 14 as well. I am considering bumping up the deployment targets of all the platforms to get rid of the versions which were not supported by apple anymore.

**Comment by Widcket** [comment]
> Tracking this in separate PR raised just now https://github.com/auth0/SimpleKeychain/pull/218 as we will have to bump up the minimum supported swift version to 5.9 and drop support for Xcode 14 as well. I am considering bumping up the deployment targets of all the platforms to get rid of the versions which were not supported by apple anymore.

I'd suggest doing that first, and then updating the list of platforms in `Platforms.swift` here (on this PR), as bumping up the minimum supported swift version to 5.9 (and dropping Xcode 14) is a prerequisite.

**Comment by desusai7** [comment]
> > Tracking this in separate PR raised just now #218 as we will have to bump up the minimum supported swift version to 5.9 and drop support for Xcode 14 as well. I am considering bumping up the deployment targets of all the platforms to get rid of the versions which were not supported by apple anymore.
> 
> I'd suggest doing that first, and then updating the list of platforms in `Platforms.swift` here (on this PR), as bumping up the minimum supported swift version to 5.9 (and dropping Xcode 14) is a prerequisite.

Done that, Can you please take a look again now ?

**Review by Widcket — APPROVED** [review]

**Pull request merged**
